services:
  api:
    build:
      context: .
    image: node:v1
    container_name: "api-container"
    ports:
      - 3000:3000
    volumes:
      - .:/user/src/app
    environment:
      NODE_ENV: development