services:
  nginx:
    build: .
    image: nginx:v1
    container_name: "web-container"
    ports:
      - 8080:80
    volumes:
      # - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    networks:
      - microservices-network

networks:
  microservices-network:
    name: microservices-network
    external: true